### ISSUE TITLE
Create google doc template based on 18F branding

### ISSUE THREAD

**Issue by amberwreed** [18F/visual-design#27]

**Comment by jenniferthibault** [comment]
This deliverable is tracked in the Brand repo. If someone is interested, I suggest using the existing issue: https://github.com/18F/brand/issues/56

**Comment by amberwreed** [comment]
Collaborators / Critique:
@jenniferthibault 
@rtwell 

Next steps:
- [ ] Show to outreach or external users to verify it meets needs
- [ ] Ask for visual designer feedback

**Comment by austinhernandez** [comment]
## Description
Create an 18F Google Doc template to be added to GSA.gov’s template gallery for documents that are on brand and for use by anyone wanting to create a document on behalf of 18F.

## User needs this meets
This template is for use for anyone within the 18F and gives them the ability to easily create documents with 18F branding

- user need: good starting point for a document to be shown to internal or external people
- user need: When employees find their work environment in line with the company values, that inspires trust, which in turn inspires loyalty, leading to a lower turnover rate and higher morale. Your business will also achieve the enviable status as being a great place to work.

## Team needs this meets
- Reduces workload of visual designers asked to polish documents. 
- Creates unified voice and style for the 18F brand which in turn creates an understanding and positive association for external clients and partners
- Enables team members across 18F to create on-brand documents faster on their own, without having a visual designer on their core team or enlisting one separately

## Support needed
- Practical users and design review

## Dependencies
- [ ] 18F style guide

## Next steps
What needs to happen to get this issue off the ground?
- [x]  Dissecting a range of 18F docs to find common patterns in existing 18F docs to make an MVP default template
- [x] Design page and create patterns and style guide 
- [ ]  Show to frequent Google Doc users (folks from outreach or biz dev teams) to verify it meets needs
- [ ] Visual designer feedback
- [ ] Role out to teams that use documents frequently then iterate

## We can close this issue when...

- [ ] Styles created for 18F that match brand guidelines (approval from visual design team)
- [ ] A templates is created that meet the need of frequent users of Google Docs
- [ ] Submit final template to  [Google Docs](https://support.google.com/docs/answer/148833#submit_template) for organization-wide use
- [ ] Released organization-wide (all hands?)

## Issue collaborators
- @jenniferthibault 
- @rtwell 

## Administrative use only
- [ ] Approved!

**Comment by austinhernandez** [comment]
WIP template can be viewed here: 
https://docs.google.com/a/gsa.gov/document/d/1BovRM6thz0YWCyd32zwbh-6TYy4ON6GEc8ILDd3RLl8/edit?usp=sharing

**Comment by austinhernandez** [comment]
## Round 1 feedback
Feedback sessions with members of UX, visual design, and outreach teams for inital thoughts on design, content, organization, and usage.

## Visual design (met on 2/10):

- Reduce the rationale - "try raw components with a little usage sprinkled in." 
- Maybe try separating sections into components (convenient for people intending to copy / paste)
- Avoid duplicate content (content that lives online and in this doc) in case of change in content elsewhere.
- Find out: Are people looking for something to duplicate or style?

**Suggestions:**
- Using styles from Google Slides 
  - [My feedback is that slides are more for on screen viewing and documents are more likely to be print.]
- Rationale is great, but cut back. try adding usage links in appendix. 

## UX (met with 2/10):

- On "synthesis" We come from a variety of backgrounds and I usually have a style I already like to work with."
- Templates may help a new practitioner to the field, but our wide mix of deliverables aren't that template-able.
- So much content might be confusing and will not work for certain user needs

**Suggestions:**
- Link to content guides in appendix

## Outreach (met with 2/13):

- Outreach, agency partnership, custom partner solutions would love this and use it often. 
- They meet directly with external stakeholders and potential clients and create a lot of one off collateral 
- There's a lot more 1:1 documentation (sales and marketing) that outreach is creating because of the slower social media and blog approval process. 
-Liked templates with explanations of why they are shaped the way they are (organizing information, hierarchy, and accessibility)

**Suggestions:** 
- Linking to slide deck
- Linking to other template
- Template for 1 pager (common artifact from those teams)
- Outline document structure suggestion:
  - Overview/Rationale info together (Here's how to use these principles in document, here's why) 
  - Then components / templates
  - Add template for one pager

**Comment by rtwell** [comment]
This is great, Austin. Damn UX snobs ;)

**Comment by amberwreed** [comment]
@austinhernandez @jenniferthibault Great work. I set up a meeting with you to discuss some minor adjustments and a rollout plan.

**Comment by amberwreed** [comment]
cc @austinhernandez @jenniferthibault 
https://github.com/18F/writing-lab/issues/240#issuecomment-289048210

**Comment by jenniferthibault** [comment]
@amberwreed following up on this—is there action you need Austin and I to take on this? Wasn't sure what the tag indicated.

**Comment by amberwreed** [comment]
@jenniferthibault Let's discuss in the huddle today. I do need help getting this wrapped up.

**Comment by jenniferthibault** [comment]
Sounds good!

**Comment by amberwreed** [comment]
To do:
- [x] Add resources to visual identity site cc @jenniferthibault 
- [x] Change doc sharing to all of 18F cc @austinhernandez 
- [ ] Ask Russ for huddle time cc @amberwreed

**Comment by jenniferthibault** [comment]
I got the visual identity site update started in https://github.com/18F/brand/pull/126 but need the final doc share links to complete it.

(Also not sure why this was closed, I think it was an accident, so I'm re-opining the issue)

**Comment by jenniferthibault** [comment]
The docs have been added to the brand site: https://pages.18f.gov/brand/templates/

Last completion criteria is to get huddle time. @amberwreed / @austinhernandez are you thinking next week or the following?

**Comment by amberwreed** [comment]
@austinhernandez @jenniferthibault Can this be closed?

**Comment by jenniferthibault** [comment]
I'd say so!
